import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { FaFacebookF, FaInstagram } from 'react-icons/fa'
import Router from 'next/router'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>THE PALM HOUSE</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <div className={styles.socials}>
        <button className={styles.socialButton} onClick={() => Router.push("https://facebook.com/ThePalmHouseCafe/?tsid=0.844890193300829&source=result")}><FaFacebookF className={styles.socialIcon}/></button>
        <button className={styles.socialButton} onClick={() => Router.push("https://instagram.com/thepalmhouse?utm_medium=copy_link")}><FaInstagram className={styles.socialIcon}/></button>
      </div>
      <div className={styles.menubox}>
        <small className={styles.small}>Lutfen seciniz/Please Choose</small>
        <div className={styles.menus}>
          <div className={styles.menu}><button onClick={() => Router.push("/food/index.html")} className={styles.menuButton}>Mönü / Menu</button></div>
          <div className={styles.menu}><button onClick={() => Router.push("/wine/index.html")} className={styles.menuButton}>Şarap Listesi / Wine List</button></div>
        </div>
        <div className={styles.logo} />
      </div>
    </div>
  )
}
