import mainMenu from "../public/food/index.html"
import Head from 'next/head'


const menu = () => {
    return (
        <div>
            <Head>
                <title>THE PALM HOUSE</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/logo.png" />
            </Head>
            <div dangerouslySetInnerHTML={{ __html: mainMenu }} />
        </div>
    )
}

export default menu
